def EXEC_ON_CONTAINER(String ContainerName, String Command){
    output= sh ( script: "docker exec  ${ContainerName}  ${Command}", returnStdout: true ).trim()
    return output
}
pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '7', artifactNumToKeepStr: '10'))
    }
    parameters {

        string(defaultValue: 'PUBLIC_CLOUD_INTERFACE_CONTAINER_JENKINS', description: 'The name of the container to execute',  name: 'ContainerName')
        string(defaultValue: 'armdocker.rnd.ericsson.se/proj-nmaas-pub/prod/public-cloud-interface:latest', description: 'Which public-cloud-interface image to pull and use', name: 'PUBLIC_CLOUD_INTERFACE_IMAGE')
        string(defaultValue: 'eu-west-2',name: 'REGION', description: 'AWS regions')
        string(defaultValue: ' ',name: 'INPUT_TEST', description: 'Input test variable, can be used to test features in the terraform templates like  ,\"enabled\": \"true\" ')

    }


    stages {
        stage("Get TAG"){
            steps {
                script{
                    REFS = sh (script: "echo ${CHANGE}| tr -d \"/\"", returnStdout: true ).trim()
                    TAG = REFS.replace("refschanges","")
                    echo TAG

                    }
                }
            }

        stage('Remove Old PCI container') {
            steps{
                script{
                    try{
                        sh (script: "docker stop  ${params.ContainerName}${TAG}${BUILD_NUMBER}")
                        sh (script: "docker rm  ${params.ContainerName}${TAG}${BUILD_NUMBER}")
                    }
                    catch(all){

                        echo "No container to remove "
                    }
                }
            }

        }
            
        stage("Run PCI container"){
            steps {
                script{
                sh (script: "docker run -d --network host --rm -t --name ${params.ContainerName}${TAG}${BUILD_NUMBER}  ${params.PUBLIC_CLOUD_INTERFACE_IMAGE}")


                }
            }
        }


        stage("Git setup"){
            steps {
                script{
                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","yum -y install git")
                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","git config --global user.email \"PDLNEMESIS@pdl.internal.ericsson.com\"")
                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","git config --global user.name \"Jenkins\"")
                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","git stash")
                }
            }
        }

        stage("Pull code review changes"){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'nemesis_functional_id', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","git pull https://${GIT_USERNAME}:${GIT_PASSWORD}@gerrit.ericsson.se/ENMaaS/enm-public-cloud/terraform-templates ${CHANGE}")
                    }
                }
            }
        }



	    stage("Creating input json"){
            steps {
                script{
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'aws_access_key', credentialsId: 'AWS_Credentials', secretKeyVariable: 'aws_secret_key']]) {
                                input_json = """
                                    |{
                                    |    \"aws_access_key\": \"${aws_access_key}\",
                                    |    \"aws_secret_key\": \"${aws_secret_key}\",
                                    |    \"provider\": \"aws\",
                                    |    \"region\": \"${params.REGION}\",
                                    |    \"component\": \"enm\",
                                    |    \"bucket\": \"ericsson-test-terraform\",
                                    |    \"key_name\": \"jenkins\",
                                    |    \"namespace\": \"ericsson\",
                                    |    \"stage\": \"${TAG}${BUILD_NUMBER}\",
                                    |    \"name\": \"jenkinscr\",
                                    |    \"enabled\": \"true\",
                                    |    \"docker_cidr_block\" : \"172.17.0.0/16\",
                                    |    \"virtual_cloud_cidr_block\": \"10.0.0.0/16\",
                                    |    \"allowed_cidr_blocks\": [\"129.192.74.5/32\", \"129.192.73.4/32\", \"79.140.216.227/32\", \"83.70.152.179/32\"],
                                    |    \"instance_type\": \"t3.medium\",
                                    |    \"max_size\": 3,
                                    |    \"min_size\": 2,
                                    |    \"kubernetes-version\": \"1.12\",
                                    |    \"elasticsearch_version\": \"6.5\",
                                    |    \"elasticsearch_ebs_volume_size\": \"10\",
                                    |    \"elasticsearch_instance_count\": \"4\",
                                    |    \"elasticsearch_iam_role_arns\": \"*\",
                                    |    \"elasticsearch_iam_actions\": [\"es:ESHttpGet\", \"es:ESHttpPut\", \"es:ESHttpPost\", \"es:ESHttpHead\", \"es:ESHttpDelete\"],
                                    |    \"elasticsearch_instance_type\": \"t2.small.elasticsearch\",
                                    |    \"elasticsearch_zone_awareness_enabled\": \"true\",
                                    |    \"elasticsearch_encrypt_at_rest_enabled\": \"false\",
                                    |    \"elasticsearch_create_iam_service_linked_role\": \"false\",
                                    |    \"elasticsearch_allow_explicit_index\": \"true\" ${params.INPUT_TEST}
                                    |}
                                    """

                                writeFile file: 'input.json', text: input_json.stripMargin("|").trim()
                                }

                            }
                        }
                    }

        stage("Write input json"){
            steps {
                script{

                	sh "docker cp input.json ${params.ContainerName}${TAG}${BUILD_NUMBER}:/root/terraform-templates/input.json"


                }
            }
        }



        stage("Hydra apply execution"){
            steps {
                script{
                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","hydra --operation all --input_file input.json")

                }
            }
        }




        stage("Copy integration playbook"){
            steps {
                script{
                        withCredentials([usernamePassword(credentialsId: 'nemesis_functional_id', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                            EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@gerrit.ericsson.se/a/ENMaaS/enm-public-cloud/terraform-wrapper-cli")
			                EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","cp -Rf terraform-wrapper-cli/integration /root/integration")
                    }
                }
            }
        }

        stage("Execute ansible playbook"){
            steps {
                script{
                    EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}", "aws eks --region eu-west-2 update-kubeconfig --name enm-${TAG}${BUILD_NUMBER}-jenkinscr-cluster")
                    EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}","ansible-playbook /root/integration/enm/enm_aws_integration.yaml -i /root/integration/enm/inventories/production/hosts")

                }
            }
        }

        stage("Run PCI destroy container"){
            steps {
                script{
                sh (script: "docker run -d --network host --rm -t --name ${params.ContainerName}${TAG}${BUILD_NUMBER}-destroy ${params.PUBLIC_CLOUD_INTERFACE_IMAGE} ")


                }
            }
        }



        stage("cp input json on destroy"){
            steps {
                script{

			        sh "docker cp input.json ${params.ContainerName}${TAG}${BUILD_NUMBER}-destroy:/root/terraform-templates/input.json"
                }
            }
        }


        stage("Hydra destroy execution"){
            steps {
                script{

			        EXEC_ON_CONTAINER("${params.ContainerName}${TAG}${BUILD_NUMBER}-destroy","hydra --operation destroy --input_file input.json")

                }
            }
        }
        stage("Remove container"){
            steps {
                script{

                    sh "docker stop ${params.ContainerName}${TAG}${BUILD_NUMBER}"
                    sh "docker stop ${params.ContainerName}${TAG}${BUILD_NUMBER}-destroy"

                }
            }
        }

    }

     post {
        success {
            gerritReview labels: [Verified: 1]
            }
        failure {
            script {
                if (env.BRANCH_NAME == 'master') {
                   emailext body: '''$DEFAULT_CONTENT
                   ${FAILURE_STATUS}
                   ${HTML_LOG_SCRIPT}''',
                   to: 'PDLNEMESIS@pdl.internal.ericsson.com',
                   subject: '$DEFAULT_SUBJECT'
                  }
                else {
                    gerritReview labels: [Verified: -1]
                   }
                }
            }

    }
}


